### PR TITLE
switched npm package polyfill for bigint to big-integer, updated Sign…

### PR DESCRIPTION
**Pull request by nicktaras**
- Switched to using this BigInt polyfill library with 0 dependancies and over 1.2 million downloads per week.

https://www.npmjs.com/package/big-integer

- Simplified the return statement of getTokenInstances() to return the web data to the webster.

### CODE REVIEW

**Comment by nicktaras** [comment]
This change fixes issue: https://github.com/TokenScript/TokenScript/issues/410

**Comment by AW-STJ** [comment]
I am unable to see the multiple tickets now, after opening multiple links. 

The attestations that I used here for reference:
https://ticket.devcon.org/?ticket=MIGZMAoCAQYCAgS4AgEBBEEEGGtH0-POR-Qv5-QmTDA4atvUi6q6Tdsintk-D4__0K8nvthVpakqgqwHeFIi2WqLBtm844fYo6jYjVEpdyuYqgNIADBFAiEAsasyaGWPALSeYd4kbw9QIOzt3OV0UvwMSG8wIDJJ2L0CIG4xdOTUcgAh_MKu73YU9X_G6sp3eR2RJmOIYNn9eR-g&secret=5781629688272492413737477838596768884403032295132741381869542447921384679885


https://ticket.devcon.org/?ticket=MIGZMAoCAQYCAgS4AgEBBEEEEIyP38Bv3vSRxhwMKFC05c3YBEZvHuXWNtZoDvD3cEUDr6NCEo-rb2HcCjQmi8jcYuAdTaxO0FXW2Sql984q2gNIADBFAiEAsasyaGWPALSeYd4kbw9QIOzt3OV0UvwMSG8wIDJJ2L0CIG4xdOTUcgAh_MKu73YU9X_G6sp3eR2RJmOIYNn9eR-g&secret=2250535841968278774110435127768627744845399703711432722728966961275290920397

**Comment by AW-STJ** [comment]
just realised that the ticket attestations that I used have same ticket IDs. Will test again with different ticket IDs and confirm

**Comment by AW-STJ** [comment]
Works correctly with attestations with different ticket IDs.

**Pull request merged**
